name: 'kernel-info-action'
description: 'retrieve the current kernel versions by category'

outputs:
  longterm:
    description: "latest longterm version"
    value: ${{ steps.receive.outputs.longterm }}
  longterm-pkg:
    description: "latest longterm package version"
    value: ${{ steps.receive.outputs.longterm-pkg }}
  stable:
    description: "latest stable version"
    value: ${{ steps.receive.outputs.stable }}
  stable-pkg:
    description: "latest stable package version"
    value: ${{ steps.receive.outputs.stable-pkg }}
  mainline:
    description: "latest mainline version"
    value: ${{ steps.receive.outputs.mainline }}
  mainline-pkg:
    description: "latest mainline package version"
    value: ${{ steps.receive.outputs.mainline-pkg }}

runs:
  using: "composite"
  steps:
    - id: receive
      shell: bash
      run: |
        PAYLOAD_LONGTERM=$(curl -s https://kernel-info.manjaro-sway.download/\?category\=longterm | jq '.[0]')
        echo "longterm=$(echo $PAYLOAD_LONGTERM | jq -r '.version')" >> $GITHUB_OUTPUT
        echo "longterm-pkg=$(echo $PAYLOAD_LONGTERM | jq -r '.packageName')" >> $GITHUB_OUTPUT

        PAYLOAD_STABLE=$(curl -s https://kernel-info.manjaro-sway.download/\?category\=stable | jq '.[0]')
        echo "stable=$(echo $PAYLOAD_STABLE | jq -r '.version')" >> $GITHUB_OUTPUT
        echo "stable-pkg=$(echo $PAYLOAD_STABLE | jq -r '.packageName')" >> $GITHUB_OUTPUT

        PAYLOAD_MAINLINE=$(curl -s https://kernel-info.manjaro-sway.download/\?category\=mainline | jq '.[0]')
        echo "mainline=$(echo $PAYLOAD_MAINLINE | jq -r '.version')" >> $GITHUB_OUTPUT
        echo "mainline-pkg=$(echo $PAYLOAD_MAINLINE | jq -r '.packageName')" >> $GITHUB_OUTPUT

    - id: list
      shell: bash
      run: |
        echo longterm: {{ steps.receive.outputs.longterm }} - ${{ steps.receive.outputs.longterm-pkg }}
        echo stable: ${{ steps.receive.outputs.stable }} - ${{ steps.receive.outputs.stable-pkg }}
        echo mainline: ${{ steps.receive.outputs.mainline }} - ${{ steps.receive.outputs.mainline-pkg }}
